[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=120
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=bbe67ff0-0574-4200-b19c-a0cccbe17415
Description=歷史的天空2015完整版（群測）
Enable=1
AutoRun=0
[Repeat]
Type=1
Number=1
[SetupUI]
Type=1
QUI=Form1
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyPress "Left", 1
Delay 0
KeyPress "Space", 1
Delay 0
KeyPress "Right", 1
Delay 0
KeyPress "Space", 1
Delay 0
KeyPress "Right", 1
Delay 0
KeyPress "Space", 1
Delay 0
