id:
title: Truly Divine Jewlery
subtitle:
description: Buffs the Gerudo Jewlery Pieces to be TRULY DIVINE!
version: 0.1
category: Armor Mods
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author: FairTech

